### ISSUE TITLE
Still struggling with migrating a pre-refinery-authentication-devise application

### ISSUE THREAD

**Issue by Atastor** [refinery/refinerycms-authentication-devise#11]
Hi, I am still struggling with migrating my pre-refinery-authentication-devise application. I described initial trouble in https://github.com/refinery/refinerycms-authentication-devise/issues/6

My current problem ist the handling of the existing refinery tables, which of course have the old names, i.e. former `refinery_roles` now is expected to be `refinery_authentication_devise_roles`, former `refinery_roles_users` now is expected to be `refinery_authentication_devise_roles_users` and so on.

My current attempt is, to tell each and every refinery model in question that it should use a table with the old name. Looking for an in-rails solution I am trying the following:
- see which refinerycms model complains first
- make a decorator for the model
- add `self.table_name="old_table_name"` to the class_eval of the decorator.
- repeat until refinerycms is content

This gets rid of the initial rails/refinerycms complaints for the first model popping up, aka `Refinery::Authentication::Devise::Role`; the decorator `refinery_authentication_devise_role_decorator.rb` contains the following code:

``` ruby
Refinery::Authentication::Devise::Role.class_eval do
  self.table_name = "refinery_roles"
end
```

And, as stated, this lets me carry on with the second refinerycms model, namely `Refinery::Authentication::Devise::RolesUsers`; the decorator `refinery_authentication_devise_roles_users_decorator.rb` contains the following code:

``` ruby
Refinery::Authentication::Devise::RolesUsers.class_eval do
  self.table_name = "refinery_roles_users"
end
```

Then, accessing the login-page fails with

> Started GET "/refb-development/login" for ::1 at 2015-08-28 11:32:40 +0200
> Processing by Refinery::Authentication::Devise::SessionsController#new as HTML
>   Parameters: {"locale"=>:de}
>    (0.4ms)  SELECT COUNT(_) FROM "refinery_images" INNER JOIN "refinery_image_translations" ON "refinery_image_translations"."refinery_image_id" = "refinery_images"."id" WHERE "refinery_image_translations"."image_alt" = 'ad-main' AND "refinery_image_translations"."locale" = ?  [["locale", "de"]]
>   Refinery::Authentication::Devise::Role Load (0.1ms)  SELECT  "refinery_roles"._ FROM "refinery_roles" WHERE "refinery_roles"."title" = ?  ORDER BY "refinery_roles"."id" ASC LIMIT 1  [["title", "Refinery"]]
> Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.5ms)
> 
> ActiveRecord::StatementInvalid (Could not find table 'refinery_authentication_devise_roles_users'):
>   activerecord (4.2.4) lib/active_record/connection_adapters/sqlite3_adapter.rb:511:in `table_structure'
>   activerecord (4.2.4) lib/active_record/connection_adapters/sqlite3_adapter.rb:385:in`columns'
>   activerecord (4.2.4) lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
>   activerecord (4.2.4) lib/active_record/connection_adapters/schema_cache.rb:49:in`columns_hash'
>   activerecord (4.2.4) lib/active_record/associations/association_scope.rb:85:in `column_for'
>   activerecord (4.2.4) lib/active_record/associations/association_scope.rb:94:in`bind'
>   activerecord (4.2.4) lib/active_record/associations/association_scope.rb:103:in `last_chain_scope'
>   activerecord (4.2.4) lib/active_record/associations/association_scope.rb:139:in`add_constraints'
>   activerecord (4.2.4) lib/active_record/associations/association_scope.rb:39:in `scope'
>   activerecord (4.2.4) lib/active_record/associations/association_scope.rb:5:in`scope'
>   activerecord (4.2.4) lib/active_record/associations/association.rb:97:in `association_scope'
>   /Users/michaelp/.rvmruby (2.2.3) bundler/gems/active_scaffold-5d513dc328a4/lib/active_scaffold/tableless.rb:45:in`association_scope_with_tableless'
>   activerecord (4.2.4) lib/active_record/associations/association.rb:86:in `scope'
>   activerecord (4.2.4) lib/active_record/associations/collection_association.rb:423:in`scope'
>   activerecord (4.2.4) lib/active_record/associations/collection_proxy.rb:37:in `initialize'
>   activerecord (4.2.4) lib/active_record/relation/delegation.rb:106:in`new'
>   activerecord (4.2.4) lib/active_record/relation/delegation.rb:106:in `create'
>   activerecord (4.2.4) lib/active_record/associations/collection_association.rb:41:in`reader'
>   activerecord (4.2.4) lib/active_record/associations/builder/association.rb:115:in `users'
>   refinerycms-authentication-devise (1.0.4) app/decorators/controllers/action_controller_base_decorator.rb:10:in`refinery_users_exist?'
>   refinerycms-authentication-devise (1.0.4) app/controllers/refinery/authentication/devise/sessions_controller.rb:32:in `force_signup_when_no_users!'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:432:in`block in make_lambda'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:164:in `call'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:164:in`block in halting'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `call'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:504:in`block in call'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `each'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:504:in`call'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:778:in`_run_process_action_callbacks'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
>   actionpack (4.2.4) lib/abstract_controller/callbacks.rb:19:in`process_action'
>   actionpack (4.2.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
>   actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:32:in`block in process_action'
>   activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
>   activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
>   activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
>   actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:30:in`process_action'
>   actionpack (4.2.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
>   activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
>   actionpack (4.2.4) lib/abstract_controller/base.rb:137:in `process'
>   actionview (4.2.4) lib/action_view/rendering.rb:30:in`process'
>   actionpack (4.2.4) lib/action_controller/metal.rb:196:in `dispatch'
>   actionpack (4.2.4) lib/action_controller/metal/rack_delegation.rb:13:in`dispatch'
>   actionpack (4.2.4) lib/action_controller/metal.rb:237:in `block in action'
>   actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in`call'
>   actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
>   actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:45:in`serve'
>   actionpack (4.2.4) lib/action_dispatch/routing/mapper.rb:49:in `serve'
>   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in`block in serve'
>   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
>   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in`serve'
>   actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
>   railties (4.2.4) lib/rails/engine.rb:518:in`call'
>   railties (4.2.4) lib/rails/railtie.rb:194:in `public_send'
>   railties (4.2.4) lib/rails/railtie.rb:194:in`method_missing'
>   actionpack (4.2.4) lib/action_dispatch/routing/mapper.rb:51:in `serve'
>   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in`block in serve'
>   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
>   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in`serve'
>   actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
>   dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in`call'
>   dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in `call'
>   warden (1.2.3) lib/warden/manager.rb:35:in`block in call'
>   warden (1.2.3) lib/warden/manager.rb:34:in `catch'
>   warden (1.2.3) lib/warden/manager.rb:34:in`call'
>   rack (1.6.4) lib/rack/etag.rb:24:in `call'
>   rack (1.6.4) lib/rack/conditionalget.rb:25:in`call'
>   rack (1.6.4) lib/rack/head.rb:13:in `call'
>   actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in`call'
>   actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
>   rack (1.6.4) lib/rack/session/abstract/id.rb:225:in`context'
>   rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
>   actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in`call'
>   activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
>   activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in`call'
>   activerecord (4.2.4) lib/active_record/migration.rb:377:in `call'
>   actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
>   activesupport (4.2.4) lib/active_support/callbacks.rb:81:in`run_callbacks'
>   actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
>   actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in`call'
>   actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
>   actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in`call'
>   actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
>   railties (4.2.4) lib/rails/rack/logger.rb:38:in`call_app'
>   railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
>   activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in`block in tagged'
>   activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
>   activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in`tagged'
>   railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
>   quiet_assets (1.1.0) lib/quiet_assets.rb:27:in`call_with_quiet_assets'
>   request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
>   actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in`call'
>   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
>   rack (1.6.4) lib/rack/runtime.rb:18:in`call'
>   activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
>   dragonfly (1.0.10) lib/dragonfly/cookie_monster.rb:9:in`call'
>   rack (1.6.4) lib/rack/lock.rb:17:in `call'
>   actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in`call'
>   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
>   railties (4.2.4) lib/rails/engine.rb:518:in`call'
>   railties (4.2.4) lib/rails/application.rb:165:in `call'
>   rack (1.6.4) lib/rack/lock.rb:17:in`call'
>   rack (1.6.4) lib/rack/content_length.rb:15:in `call'
>   rack (1.6.4) lib/rack/handler/webrick.rb:88:in`service'
>   /Users/michaelp/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
>   /Users/michaelp/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in`run'
>   /Users/michaelp/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

I will gladly receive any suggestions about
- how to tackle the problem
- where to find the problem
- which alternative route in my migration project I could/should take

Thanks a lot in advance
Michael

**Comment by Atastor** [comment]
Ok, I got a solution, wrapping it up and will post it then with a pull request; won't be before Sunday evening.

I added configurable options describing the tables used for `Roles` and `RolesUsers` to `refinerycms-authentication-devise`
