### ISSUE TITLE
Not able to display a page in production mode

### ISSUE THREAD

**Issue by bricesanchez** [refinery/refinerycms-authentication-devise#4]
I'm not able to display a page in production mode on a dummy app with this extension

This is my stacktrace : 

```shell
I, [2015-05-27T14:20:47.074676 #46288]  INFO -- : Started GET "/accueil" for ::1 at 2015-05-27 14:20:47 -0400
I, [2015-05-27T14:20:48.688389 #46288]  INFO -- : Processing by Refinery::PagesController#show as HTML
I, [2015-05-27T14:20:48.688483 #46288]  INFO -- :   Parameters: {"path"=>"accueil", "locale"=>:en}
D, [2015-05-27T14:20:48.710431 #46288] DEBUG -- :   Refinery::Authentication::Devise::User Load (0.4ms)  SELECT  "refinery_authentication_devise_users".* FROM "refinery_authentication_devise_users" WHERE "refinery_authentication_devise_users"."id" = ?  ORDER BY "refinery_authentication_devise_users"."id" ASC LIMIT 1  [["id", 1]]
D, [2015-05-27T14:20:48.740455 #46288] DEBUG -- :   Refinery::Page Load (0.9ms)  SELECT  "refinery_pages".* FROM "refinery_pages" INNER JOIN "refinery_page_translations" ON "refinery_page_translations"."refinery_page_id" = "refinery_pages"."id" WHERE "refinery_pages"."parent_id" IS NULL AND "refinery_page_translations"."locale" = 'en' AND "refinery_page_translations"."slug" = 'accueil'  ORDER BY "refinery_pages"."id" ASC LIMIT 1
D, [2015-05-27T14:20:48.804480 #46288] DEBUG -- :   Refinery::Page::Translation Load (0.4ms)  SELECT "refinery_page_translations".* FROM "refinery_page_translations" WHERE "refinery_page_translations"."refinery_page_id" = ?  [["refinery_page_id", 1]]
D, [2015-05-27T14:20:48.821242 #46288] DEBUG -- :   Refinery::Page Load (0.5ms)  SELECT  "refinery_pages".* FROM "refinery_pages" WHERE ("refinery_pages"."lft" <= 1) AND ("refinery_pages"."rgt" >= 2) AND "refinery_pages"."parent_id" IS NULL  ORDER BY "refinery_pages"."lft" LIMIT 1
D, [2015-05-27T14:20:48.822779 #46288] DEBUG -- :   CACHE (0.0ms)  SELECT "refinery_page_translations".* FROM "refinery_page_translations" WHERE "refinery_page_translations"."refinery_page_id" = ?  [["refinery_page_id", 1]]
I, [2015-05-27T14:20:48.907695 #46288]  INFO -- :   Rendered /Users/bci20/Sites/refinery/refinerycms-authentication-devise/.gems/bundler/gems/refinerycms-c5e7a052c867/core/app/views/refinery/_content_page.html.erb (51.4ms)
I, [2015-05-27T14:20:48.907833 #46288]  INFO -- :   Rendered /Users/bci20/Sites/refinery/refinerycms-authentication-devise/.gems/bundler/gems/refinerycms-c5e7a052c867/pages/app/views/refinery/pages/show.html.erb within layouts/application (61.1ms)
I, [2015-05-27T14:20:48.908119 #46288]  INFO -- : Completed 500 Internal Server Error in 219ms (ActiveRecord: 3.9ms)
F, [2015-05-27T14:20:48.910431 #46288] FATAL -- : 
ActionView::Template::Error (undefined local variable or method `page_title' for #<#<Class:0x007fb313520fa8>:0x007fb313520238>):
    1: <%= render_content_page(@page, {
    2:       :hide_sections => local_assigns[:hide_sections],
    3:       :can_use_fallback => !local_assigns[:show_empty_sections] && !local_assigns[:remove_automatic_sections]
    4:     }) %>
  /Users/bci20/Sites/refinery/refinerycms-authentication-devise/.gems/bundler/gems/refinerycms-c5e7a052c867/pages/app/helpers/refinery/pages/content_pages_helper.rb:9:in `render_content_page'
  /Users/bci20/Sites/refinery/refinerycms-authentication-devise/.gems/bundler/gems/refinerycms-c5e7a052c867/core/app/views/refinery/_content_page.html.erb:1:in `___sers_bci____ites_refinery_refinerycms_authentication_devise__gems_bundler_gems_refinerycms_c_e_a___c____core_app_views_refinery__content_page_html_erb___2848640863599038591_70203549900320'
  actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.1) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  /Users/bci20/Sites/refinery/refinerycms-authentication-devise/.gems/bundler/gems/refinerycms-c5e7a052c867/pages/app/views/refinery/pages/show.html.erb:1:in `___sers_bci____ites_refinery_refinerycms_authentication_devise__gems_bundler_gems_refinerycms_c_e_a___c____pages_app_views_refinery_pages_show_html_erb__274115027582767637_70203547272900'
  actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/bci20/.rbenv/versions/2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  /Users/bci20/Sites/refinery/refinerycms-authentication-devise/.gems/bundler/gems/refinerycms-c5e7a052c867/pages/lib/refinery/pages/instance_methods.rb:33:in `render_with_presenters'
  /Users/bci20/Sites/refinery/refinerycms-authentication-devise/.gems/bundler/gems/refinerycms-c5e7a052c867/pages/lib/refinery/pages/render_options.rb:20:in `render_with_templates?'
  /Users/bci20/Sites/refinery/refinerycms-authentication-devise/.gems/bundler/gems/refinerycms-c5e7a052c867/pages/app/controllers/refinery/pages_controller.rb:35:in `show'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in `call'
  dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.1) lib/rack/etag.rb:24:in `call'
  rack (1.6.1) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.1) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
  dragonfly (1.0.10) lib/dragonfly/cookie_monster.rb:9:in `call'
  rack (1.6.1) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.1) lib/rack/lock.rb:17:in `call'
  rack (1.6.1) lib/rack/content_length.rb:15:in `call'
  rack (1.6.1) lib/rack/handler/webrick.rb:89:in `service'
  /Users/bci20/.rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/bci20/.rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/bci20/.rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

I've tested this extension because i'm facing undefined method errors on our spree-refinery-authentication extension in production mode only too :

This my other stacktrace with our spree-refinery-authentication extension :

```shell
cache error: No server available
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/dalli-2.7.4/lib/dalli/ring.rb:45:in `server_for_key'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/dalli-2.7.4/lib/dalli/client.rb:332:in `perform'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/dalli-2.7.4/lib/dalli/client.rb:56:in `get'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/memcache.rb:48:in `block (4 levels) in instrument_methods'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer.rb:69:in `block in trace_execution_scoped'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer.rb:67:in `trace_execution_scoped'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/memcache.rb:45:in `block (3 levels) in instrument_methods'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-cache-1.2/lib/rack/cache/metastore.rb:324:in `read'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-cache-1.2/lib/rack/cache/metastore.rb:30:in `lookup'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-cache-1.2/lib/rack/cache/context.rb:169:in `lookup'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.1/lib/rack/sendfile.rb:113:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.1/lib/rack/content_length.rb:15:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/puma-2.11.3/lib/puma/server.rb:507:in `handle_request'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/puma-2.11.3/lib/puma/server.rb:375:in `process_client'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/puma-2.11.3/lib/puma/server.rb:262:in `block in run'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
Started GET "/" for ::1 at 2015-05-27 14:28:26 -0400
Processing by Refinery::PagesController#home as HTML
  Rendered refinery/pages/home.html.slim within layouts/application (1.4ms)
  Rendered .gems/bundler/gems/refinerycms-c5e7a052c867/core/app/views/refinery/_html_tag.html.erb (0.4ms)
  Rendered .gems/bundler/gems/refinerycms-c5e7a052c867/core/app/views/refinery/_site_bar.html.erb (261.6ms)
Completed 500 Internal Server Error in 275ms (ActiveRecord: 1.8ms)

ActionView::Template::Error (undefined method `display_site_bar?' for #<#<Class:0x007ffb0f93de58>:0x007ffb093192a8>):
    1: <% if display_site_bar? %>
    2:   <% unless admin? # all required JS included by backend. %>
    3:     <% content_for :stylesheets, stylesheet_link_tag('refinery/site_bar') unless !!local_assigns[:exclude_css] %>
    4:     <%= yield(:stylesheets) unless local_assigns[:head] || local_assigns[:exclude_css] %>
  app/views/layouts/application.html.slim:3:in `_aacb91b860ea02c48166b4689e87d139'


cache: [GET /] pass
```

Any idea @parndt ? Are they related errors ?

**Comment by bricesanchez** [comment]
When i set `config.eager_load = false` in production mode, it work.

I've started to read this : 
http://blog.arkency.com/2014/11/dont-forget-about-eager-load-when-extending-autoload/

**Comment by bricesanchez** [comment]
It has been fixed : https://github.com/refinery/refinerycms/pull/2940#issuecomment-119740264
